// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DBProtocol.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_DBProtocol_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_DBProtocol_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021009 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "Struct.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_DBProtocol_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_DBProtocol_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_DBProtocol_2eproto;
namespace DBProtocol {
class C_LOAD_LOBBY_PLAYERS_INFO;
struct C_LOAD_LOBBY_PLAYERS_INFODefaultTypeInternal;
extern C_LOAD_LOBBY_PLAYERS_INFODefaultTypeInternal _C_LOAD_LOBBY_PLAYERS_INFO_default_instance_;
class S_LOAD_LOBBY_PLAYERS_INFO;
struct S_LOAD_LOBBY_PLAYERS_INFODefaultTypeInternal;
extern S_LOAD_LOBBY_PLAYERS_INFODefaultTypeInternal _S_LOAD_LOBBY_PLAYERS_INFO_default_instance_;
}  // namespace DBProtocol
PROTOBUF_NAMESPACE_OPEN
template<> ::DBProtocol::C_LOAD_LOBBY_PLAYERS_INFO* Arena::CreateMaybeMessage<::DBProtocol::C_LOAD_LOBBY_PLAYERS_INFO>(Arena*);
template<> ::DBProtocol::S_LOAD_LOBBY_PLAYERS_INFO* Arena::CreateMaybeMessage<::DBProtocol::S_LOAD_LOBBY_PLAYERS_INFO>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace DBProtocol {

// ===================================================================

class C_LOAD_LOBBY_PLAYERS_INFO final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:DBProtocol.C_LOAD_LOBBY_PLAYERS_INFO) */ {
 public:
  inline C_LOAD_LOBBY_PLAYERS_INFO() : C_LOAD_LOBBY_PLAYERS_INFO(nullptr) {}
  ~C_LOAD_LOBBY_PLAYERS_INFO() override;
  explicit PROTOBUF_CONSTEXPR C_LOAD_LOBBY_PLAYERS_INFO(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  C_LOAD_LOBBY_PLAYERS_INFO(const C_LOAD_LOBBY_PLAYERS_INFO& from);
  C_LOAD_LOBBY_PLAYERS_INFO(C_LOAD_LOBBY_PLAYERS_INFO&& from) noexcept
    : C_LOAD_LOBBY_PLAYERS_INFO() {
    *this = ::std::move(from);
  }

  inline C_LOAD_LOBBY_PLAYERS_INFO& operator=(const C_LOAD_LOBBY_PLAYERS_INFO& from) {
    CopyFrom(from);
    return *this;
  }
  inline C_LOAD_LOBBY_PLAYERS_INFO& operator=(C_LOAD_LOBBY_PLAYERS_INFO&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const C_LOAD_LOBBY_PLAYERS_INFO& default_instance() {
    return *internal_default_instance();
  }
  static inline const C_LOAD_LOBBY_PLAYERS_INFO* internal_default_instance() {
    return reinterpret_cast<const C_LOAD_LOBBY_PLAYERS_INFO*>(
               &_C_LOAD_LOBBY_PLAYERS_INFO_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(C_LOAD_LOBBY_PLAYERS_INFO& a, C_LOAD_LOBBY_PLAYERS_INFO& b) {
    a.Swap(&b);
  }
  inline void Swap(C_LOAD_LOBBY_PLAYERS_INFO* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(C_LOAD_LOBBY_PLAYERS_INFO* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  C_LOAD_LOBBY_PLAYERS_INFO* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<C_LOAD_LOBBY_PLAYERS_INFO>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const C_LOAD_LOBBY_PLAYERS_INFO& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const C_LOAD_LOBBY_PLAYERS_INFO& from) {
    C_LOAD_LOBBY_PLAYERS_INFO::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(C_LOAD_LOBBY_PLAYERS_INFO* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "DBProtocol.C_LOAD_LOBBY_PLAYERS_INFO";
  }
  protected:
  explicit C_LOAD_LOBBY_PLAYERS_INFO(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAccountFieldNumber = 1,
  };
  // string account = 1;
  void clear_account();
  const std::string& account() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_account(ArgT0&& arg0, ArgT... args);
  std::string* mutable_account();
  PROTOBUF_NODISCARD std::string* release_account();
  void set_allocated_account(std::string* account);
  private:
  const std::string& _internal_account() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_account(const std::string& value);
  std::string* _internal_mutable_account();
  public:

  // @@protoc_insertion_point(class_scope:DBProtocol.C_LOAD_LOBBY_PLAYERS_INFO)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr account_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_DBProtocol_2eproto;
};
// -------------------------------------------------------------------

class S_LOAD_LOBBY_PLAYERS_INFO final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:DBProtocol.S_LOAD_LOBBY_PLAYERS_INFO) */ {
 public:
  inline S_LOAD_LOBBY_PLAYERS_INFO() : S_LOAD_LOBBY_PLAYERS_INFO(nullptr) {}
  ~S_LOAD_LOBBY_PLAYERS_INFO() override;
  explicit PROTOBUF_CONSTEXPR S_LOAD_LOBBY_PLAYERS_INFO(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  S_LOAD_LOBBY_PLAYERS_INFO(const S_LOAD_LOBBY_PLAYERS_INFO& from);
  S_LOAD_LOBBY_PLAYERS_INFO(S_LOAD_LOBBY_PLAYERS_INFO&& from) noexcept
    : S_LOAD_LOBBY_PLAYERS_INFO() {
    *this = ::std::move(from);
  }

  inline S_LOAD_LOBBY_PLAYERS_INFO& operator=(const S_LOAD_LOBBY_PLAYERS_INFO& from) {
    CopyFrom(from);
    return *this;
  }
  inline S_LOAD_LOBBY_PLAYERS_INFO& operator=(S_LOAD_LOBBY_PLAYERS_INFO&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S_LOAD_LOBBY_PLAYERS_INFO& default_instance() {
    return *internal_default_instance();
  }
  static inline const S_LOAD_LOBBY_PLAYERS_INFO* internal_default_instance() {
    return reinterpret_cast<const S_LOAD_LOBBY_PLAYERS_INFO*>(
               &_S_LOAD_LOBBY_PLAYERS_INFO_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(S_LOAD_LOBBY_PLAYERS_INFO& a, S_LOAD_LOBBY_PLAYERS_INFO& b) {
    a.Swap(&b);
  }
  inline void Swap(S_LOAD_LOBBY_PLAYERS_INFO* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S_LOAD_LOBBY_PLAYERS_INFO* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  S_LOAD_LOBBY_PLAYERS_INFO* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<S_LOAD_LOBBY_PLAYERS_INFO>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const S_LOAD_LOBBY_PLAYERS_INFO& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const S_LOAD_LOBBY_PLAYERS_INFO& from) {
    S_LOAD_LOBBY_PLAYERS_INFO::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(S_LOAD_LOBBY_PLAYERS_INFO* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "DBProtocol.S_LOAD_LOBBY_PLAYERS_INFO";
  }
  protected:
  explicit S_LOAD_LOBBY_PLAYERS_INFO(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kInfosFieldNumber = 1,
  };
  // repeated .Protocol.LobbyPlayerInfo infos = 1;
  int infos_size() const;
  private:
  int _internal_infos_size() const;
  public:
  void clear_infos();
  ::Protocol::LobbyPlayerInfo* mutable_infos(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::LobbyPlayerInfo >*
      mutable_infos();
  private:
  const ::Protocol::LobbyPlayerInfo& _internal_infos(int index) const;
  ::Protocol::LobbyPlayerInfo* _internal_add_infos();
  public:
  const ::Protocol::LobbyPlayerInfo& infos(int index) const;
  ::Protocol::LobbyPlayerInfo* add_infos();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::LobbyPlayerInfo >&
      infos() const;

  // @@protoc_insertion_point(class_scope:DBProtocol.S_LOAD_LOBBY_PLAYERS_INFO)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::LobbyPlayerInfo > infos_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_DBProtocol_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// C_LOAD_LOBBY_PLAYERS_INFO

// string account = 1;
inline void C_LOAD_LOBBY_PLAYERS_INFO::clear_account() {
  _impl_.account_.ClearToEmpty();
}
inline const std::string& C_LOAD_LOBBY_PLAYERS_INFO::account() const {
  // @@protoc_insertion_point(field_get:DBProtocol.C_LOAD_LOBBY_PLAYERS_INFO.account)
  return _internal_account();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void C_LOAD_LOBBY_PLAYERS_INFO::set_account(ArgT0&& arg0, ArgT... args) {
 
 _impl_.account_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:DBProtocol.C_LOAD_LOBBY_PLAYERS_INFO.account)
}
inline std::string* C_LOAD_LOBBY_PLAYERS_INFO::mutable_account() {
  std::string* _s = _internal_mutable_account();
  // @@protoc_insertion_point(field_mutable:DBProtocol.C_LOAD_LOBBY_PLAYERS_INFO.account)
  return _s;
}
inline const std::string& C_LOAD_LOBBY_PLAYERS_INFO::_internal_account() const {
  return _impl_.account_.Get();
}
inline void C_LOAD_LOBBY_PLAYERS_INFO::_internal_set_account(const std::string& value) {
  
  _impl_.account_.Set(value, GetArenaForAllocation());
}
inline std::string* C_LOAD_LOBBY_PLAYERS_INFO::_internal_mutable_account() {
  
  return _impl_.account_.Mutable(GetArenaForAllocation());
}
inline std::string* C_LOAD_LOBBY_PLAYERS_INFO::release_account() {
  // @@protoc_insertion_point(field_release:DBProtocol.C_LOAD_LOBBY_PLAYERS_INFO.account)
  return _impl_.account_.Release();
}
inline void C_LOAD_LOBBY_PLAYERS_INFO::set_allocated_account(std::string* account) {
  if (account != nullptr) {
    
  } else {
    
  }
  _impl_.account_.SetAllocated(account, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.account_.IsDefault()) {
    _impl_.account_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:DBProtocol.C_LOAD_LOBBY_PLAYERS_INFO.account)
}

// -------------------------------------------------------------------

// S_LOAD_LOBBY_PLAYERS_INFO

// repeated .Protocol.LobbyPlayerInfo infos = 1;
inline int S_LOAD_LOBBY_PLAYERS_INFO::_internal_infos_size() const {
  return _impl_.infos_.size();
}
inline int S_LOAD_LOBBY_PLAYERS_INFO::infos_size() const {
  return _internal_infos_size();
}
inline ::Protocol::LobbyPlayerInfo* S_LOAD_LOBBY_PLAYERS_INFO::mutable_infos(int index) {
  // @@protoc_insertion_point(field_mutable:DBProtocol.S_LOAD_LOBBY_PLAYERS_INFO.infos)
  return _impl_.infos_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::LobbyPlayerInfo >*
S_LOAD_LOBBY_PLAYERS_INFO::mutable_infos() {
  // @@protoc_insertion_point(field_mutable_list:DBProtocol.S_LOAD_LOBBY_PLAYERS_INFO.infos)
  return &_impl_.infos_;
}
inline const ::Protocol::LobbyPlayerInfo& S_LOAD_LOBBY_PLAYERS_INFO::_internal_infos(int index) const {
  return _impl_.infos_.Get(index);
}
inline const ::Protocol::LobbyPlayerInfo& S_LOAD_LOBBY_PLAYERS_INFO::infos(int index) const {
  // @@protoc_insertion_point(field_get:DBProtocol.S_LOAD_LOBBY_PLAYERS_INFO.infos)
  return _internal_infos(index);
}
inline ::Protocol::LobbyPlayerInfo* S_LOAD_LOBBY_PLAYERS_INFO::_internal_add_infos() {
  return _impl_.infos_.Add();
}
inline ::Protocol::LobbyPlayerInfo* S_LOAD_LOBBY_PLAYERS_INFO::add_infos() {
  ::Protocol::LobbyPlayerInfo* _add = _internal_add_infos();
  // @@protoc_insertion_point(field_add:DBProtocol.S_LOAD_LOBBY_PLAYERS_INFO.infos)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Protocol::LobbyPlayerInfo >&
S_LOAD_LOBBY_PLAYERS_INFO::infos() const {
  // @@protoc_insertion_point(field_list:DBProtocol.S_LOAD_LOBBY_PLAYERS_INFO.infos)
  return _impl_.infos_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace DBProtocol

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_DBProtocol_2eproto
