// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DBProtocol.proto

#include "DBProtocol.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace DBProtocol {
PROTOBUF_CONSTEXPR C_LOAD_LOBBY_PLAYERS_INFO::C_LOAD_LOBBY_PLAYERS_INFO(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.account_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct C_LOAD_LOBBY_PLAYERS_INFODefaultTypeInternal {
  PROTOBUF_CONSTEXPR C_LOAD_LOBBY_PLAYERS_INFODefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~C_LOAD_LOBBY_PLAYERS_INFODefaultTypeInternal() {}
  union {
    C_LOAD_LOBBY_PLAYERS_INFO _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 C_LOAD_LOBBY_PLAYERS_INFODefaultTypeInternal _C_LOAD_LOBBY_PLAYERS_INFO_default_instance_;
PROTOBUF_CONSTEXPR S_LOAD_LOBBY_PLAYERS_INFO::S_LOAD_LOBBY_PLAYERS_INFO(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.infos_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct S_LOAD_LOBBY_PLAYERS_INFODefaultTypeInternal {
  PROTOBUF_CONSTEXPR S_LOAD_LOBBY_PLAYERS_INFODefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~S_LOAD_LOBBY_PLAYERS_INFODefaultTypeInternal() {}
  union {
    S_LOAD_LOBBY_PLAYERS_INFO _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 S_LOAD_LOBBY_PLAYERS_INFODefaultTypeInternal _S_LOAD_LOBBY_PLAYERS_INFO_default_instance_;
}  // namespace DBProtocol
static ::_pb::Metadata file_level_metadata_DBProtocol_2eproto[2];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_DBProtocol_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_DBProtocol_2eproto = nullptr;

const uint32_t TableStruct_DBProtocol_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::DBProtocol::C_LOAD_LOBBY_PLAYERS_INFO, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::DBProtocol::C_LOAD_LOBBY_PLAYERS_INFO, _impl_.account_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::DBProtocol::S_LOAD_LOBBY_PLAYERS_INFO, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::DBProtocol::S_LOAD_LOBBY_PLAYERS_INFO, _impl_.infos_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::DBProtocol::C_LOAD_LOBBY_PLAYERS_INFO)},
  { 7, -1, -1, sizeof(::DBProtocol::S_LOAD_LOBBY_PLAYERS_INFO)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::DBProtocol::_C_LOAD_LOBBY_PLAYERS_INFO_default_instance_._instance,
  &::DBProtocol::_S_LOAD_LOBBY_PLAYERS_INFO_default_instance_._instance,
};

const char descriptor_table_protodef_DBProtocol_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\020DBProtocol.proto\022\nDBProtocol\032\014Struct.p"
  "roto\",\n\031C_LOAD_LOBBY_PLAYERS_INFO\022\017\n\007acc"
  "ount\030\001 \001(\t\"E\n\031S_LOAD_LOBBY_PLAYERS_INFO\022"
  "(\n\005infos\030\001 \003(\0132\031.Protocol.LobbyPlayerInf"
  "ob\006proto3"
  ;
static const ::_pbi::DescriptorTable* const descriptor_table_DBProtocol_2eproto_deps[1] = {
  &::descriptor_table_Struct_2eproto,
};
static ::_pbi::once_flag descriptor_table_DBProtocol_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_DBProtocol_2eproto = {
    false, false, 169, descriptor_table_protodef_DBProtocol_2eproto,
    "DBProtocol.proto",
    &descriptor_table_DBProtocol_2eproto_once, descriptor_table_DBProtocol_2eproto_deps, 1, 2,
    schemas, file_default_instances, TableStruct_DBProtocol_2eproto::offsets,
    file_level_metadata_DBProtocol_2eproto, file_level_enum_descriptors_DBProtocol_2eproto,
    file_level_service_descriptors_DBProtocol_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_DBProtocol_2eproto_getter() {
  return &descriptor_table_DBProtocol_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_DBProtocol_2eproto(&descriptor_table_DBProtocol_2eproto);
namespace DBProtocol {

// ===================================================================

class C_LOAD_LOBBY_PLAYERS_INFO::_Internal {
 public:
};

C_LOAD_LOBBY_PLAYERS_INFO::C_LOAD_LOBBY_PLAYERS_INFO(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:DBProtocol.C_LOAD_LOBBY_PLAYERS_INFO)
}
C_LOAD_LOBBY_PLAYERS_INFO::C_LOAD_LOBBY_PLAYERS_INFO(const C_LOAD_LOBBY_PLAYERS_INFO& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  C_LOAD_LOBBY_PLAYERS_INFO* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.account_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.account_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.account_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_account().empty()) {
    _this->_impl_.account_.Set(from._internal_account(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:DBProtocol.C_LOAD_LOBBY_PLAYERS_INFO)
}

inline void C_LOAD_LOBBY_PLAYERS_INFO::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.account_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.account_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.account_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

C_LOAD_LOBBY_PLAYERS_INFO::~C_LOAD_LOBBY_PLAYERS_INFO() {
  // @@protoc_insertion_point(destructor:DBProtocol.C_LOAD_LOBBY_PLAYERS_INFO)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void C_LOAD_LOBBY_PLAYERS_INFO::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.account_.Destroy();
}

void C_LOAD_LOBBY_PLAYERS_INFO::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void C_LOAD_LOBBY_PLAYERS_INFO::Clear() {
// @@protoc_insertion_point(message_clear_start:DBProtocol.C_LOAD_LOBBY_PLAYERS_INFO)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.account_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* C_LOAD_LOBBY_PLAYERS_INFO::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string account = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_account();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "DBProtocol.C_LOAD_LOBBY_PLAYERS_INFO.account"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* C_LOAD_LOBBY_PLAYERS_INFO::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:DBProtocol.C_LOAD_LOBBY_PLAYERS_INFO)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string account = 1;
  if (!this->_internal_account().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_account().data(), static_cast<int>(this->_internal_account().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "DBProtocol.C_LOAD_LOBBY_PLAYERS_INFO.account");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_account(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:DBProtocol.C_LOAD_LOBBY_PLAYERS_INFO)
  return target;
}

size_t C_LOAD_LOBBY_PLAYERS_INFO::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:DBProtocol.C_LOAD_LOBBY_PLAYERS_INFO)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string account = 1;
  if (!this->_internal_account().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_account());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData C_LOAD_LOBBY_PLAYERS_INFO::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    C_LOAD_LOBBY_PLAYERS_INFO::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*C_LOAD_LOBBY_PLAYERS_INFO::GetClassData() const { return &_class_data_; }


void C_LOAD_LOBBY_PLAYERS_INFO::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<C_LOAD_LOBBY_PLAYERS_INFO*>(&to_msg);
  auto& from = static_cast<const C_LOAD_LOBBY_PLAYERS_INFO&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:DBProtocol.C_LOAD_LOBBY_PLAYERS_INFO)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_account().empty()) {
    _this->_internal_set_account(from._internal_account());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void C_LOAD_LOBBY_PLAYERS_INFO::CopyFrom(const C_LOAD_LOBBY_PLAYERS_INFO& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:DBProtocol.C_LOAD_LOBBY_PLAYERS_INFO)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool C_LOAD_LOBBY_PLAYERS_INFO::IsInitialized() const {
  return true;
}

void C_LOAD_LOBBY_PLAYERS_INFO::InternalSwap(C_LOAD_LOBBY_PLAYERS_INFO* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.account_, lhs_arena,
      &other->_impl_.account_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata C_LOAD_LOBBY_PLAYERS_INFO::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_DBProtocol_2eproto_getter, &descriptor_table_DBProtocol_2eproto_once,
      file_level_metadata_DBProtocol_2eproto[0]);
}

// ===================================================================

class S_LOAD_LOBBY_PLAYERS_INFO::_Internal {
 public:
};

void S_LOAD_LOBBY_PLAYERS_INFO::clear_infos() {
  _impl_.infos_.Clear();
}
S_LOAD_LOBBY_PLAYERS_INFO::S_LOAD_LOBBY_PLAYERS_INFO(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:DBProtocol.S_LOAD_LOBBY_PLAYERS_INFO)
}
S_LOAD_LOBBY_PLAYERS_INFO::S_LOAD_LOBBY_PLAYERS_INFO(const S_LOAD_LOBBY_PLAYERS_INFO& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  S_LOAD_LOBBY_PLAYERS_INFO* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.infos_){from._impl_.infos_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:DBProtocol.S_LOAD_LOBBY_PLAYERS_INFO)
}

inline void S_LOAD_LOBBY_PLAYERS_INFO::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.infos_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

S_LOAD_LOBBY_PLAYERS_INFO::~S_LOAD_LOBBY_PLAYERS_INFO() {
  // @@protoc_insertion_point(destructor:DBProtocol.S_LOAD_LOBBY_PLAYERS_INFO)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void S_LOAD_LOBBY_PLAYERS_INFO::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.infos_.~RepeatedPtrField();
}

void S_LOAD_LOBBY_PLAYERS_INFO::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void S_LOAD_LOBBY_PLAYERS_INFO::Clear() {
// @@protoc_insertion_point(message_clear_start:DBProtocol.S_LOAD_LOBBY_PLAYERS_INFO)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.infos_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* S_LOAD_LOBBY_PLAYERS_INFO::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .Protocol.LobbyPlayerInfo infos = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_infos(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* S_LOAD_LOBBY_PLAYERS_INFO::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:DBProtocol.S_LOAD_LOBBY_PLAYERS_INFO)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .Protocol.LobbyPlayerInfo infos = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_infos_size()); i < n; i++) {
    const auto& repfield = this->_internal_infos(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:DBProtocol.S_LOAD_LOBBY_PLAYERS_INFO)
  return target;
}

size_t S_LOAD_LOBBY_PLAYERS_INFO::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:DBProtocol.S_LOAD_LOBBY_PLAYERS_INFO)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .Protocol.LobbyPlayerInfo infos = 1;
  total_size += 1UL * this->_internal_infos_size();
  for (const auto& msg : this->_impl_.infos_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData S_LOAD_LOBBY_PLAYERS_INFO::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    S_LOAD_LOBBY_PLAYERS_INFO::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*S_LOAD_LOBBY_PLAYERS_INFO::GetClassData() const { return &_class_data_; }


void S_LOAD_LOBBY_PLAYERS_INFO::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<S_LOAD_LOBBY_PLAYERS_INFO*>(&to_msg);
  auto& from = static_cast<const S_LOAD_LOBBY_PLAYERS_INFO&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:DBProtocol.S_LOAD_LOBBY_PLAYERS_INFO)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.infos_.MergeFrom(from._impl_.infos_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void S_LOAD_LOBBY_PLAYERS_INFO::CopyFrom(const S_LOAD_LOBBY_PLAYERS_INFO& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:DBProtocol.S_LOAD_LOBBY_PLAYERS_INFO)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool S_LOAD_LOBBY_PLAYERS_INFO::IsInitialized() const {
  return true;
}

void S_LOAD_LOBBY_PLAYERS_INFO::InternalSwap(S_LOAD_LOBBY_PLAYERS_INFO* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.infos_.InternalSwap(&other->_impl_.infos_);
}

::PROTOBUF_NAMESPACE_ID::Metadata S_LOAD_LOBBY_PLAYERS_INFO::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_DBProtocol_2eproto_getter, &descriptor_table_DBProtocol_2eproto_once,
      file_level_metadata_DBProtocol_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace DBProtocol
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::DBProtocol::C_LOAD_LOBBY_PLAYERS_INFO*
Arena::CreateMaybeMessage< ::DBProtocol::C_LOAD_LOBBY_PLAYERS_INFO >(Arena* arena) {
  return Arena::CreateMessageInternal< ::DBProtocol::C_LOAD_LOBBY_PLAYERS_INFO >(arena);
}
template<> PROTOBUF_NOINLINE ::DBProtocol::S_LOAD_LOBBY_PLAYERS_INFO*
Arena::CreateMaybeMessage< ::DBProtocol::S_LOAD_LOBBY_PLAYERS_INFO >(Arena* arena) {
  return Arena::CreateMessageInternal< ::DBProtocol::S_LOAD_LOBBY_PLAYERS_INFO >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
